In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9230, 5365, 1870, 6791],
 [9230, 5365, 1870, 5742],
 [9230, 7396, 1870, 6190],
 [4328, 968, 9161, 5257, 8536],
 [4328, 968, 9161, 5257, 6552],
 [5601, 9230, 6555, 1870, 8450],
 [7048, 3393, 361, 5257]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9230 5365 1870 6791]
 [   0    0    0    0 9230 5365 1870 5742]
 [   0    0    0    0 9230 7396 1870 6190]
 [   0    0    0 4328  968 9161 5257 8536]
 [   0    0    0 4328  968 9161 5257 6552]
 [   0    0    0 5601 9230 6555 1870 8450]
 [   0    0    0    0 7048 3393  361 5257]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 125ms/step


array([[[-0.00454841, -0.0458563 ,  0.04385321,  0.02485174,
          0.03006113, -0.01859785, -0.01245942,  0.01755248,
          0.04559081, -0.03148939],
        [-0.00454841, -0.0458563 ,  0.04385321,  0.02485174,
          0.03006113, -0.01859785, -0.01245942,  0.01755248,
          0.04559081, -0.03148939],
        [-0.00454841, -0.0458563 ,  0.04385321,  0.02485174,
          0.03006113, -0.01859785, -0.01245942,  0.01755248,
          0.04559081, -0.03148939],
        [-0.00454841, -0.0458563 ,  0.04385321,  0.02485174,
          0.03006113, -0.01859785, -0.01245942,  0.01755248,
          0.04559081, -0.03148939],
        [ 0.01791817, -0.01954323, -0.0439586 , -0.01066151,
         -0.00040602, -0.02125261, -0.02847081,  0.04438033,
          0.02990146,  0.02927512],
        [ 0.02614791, -0.015311  , -0.02671999, -0.01079929,
          0.01963147, -0.04251781,  0.01549606,  0.00074265,
         -0.01068414,  0.03010098],
        [ 0.00789253, -0.04971359, -0.00026793,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9230, 5365, 1870, 6791], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 25ms/step


array([[-0.00454841, -0.0458563 ,  0.04385321,  0.02485174,  0.03006113,
        -0.01859785, -0.01245942,  0.01755248,  0.04559081, -0.03148939],
       [-0.00454841, -0.0458563 ,  0.04385321,  0.02485174,  0.03006113,
        -0.01859785, -0.01245942,  0.01755248,  0.04559081, -0.03148939],
       [-0.00454841, -0.0458563 ,  0.04385321,  0.02485174,  0.03006113,
        -0.01859785, -0.01245942,  0.01755248,  0.04559081, -0.03148939],
       [-0.00454841, -0.0458563 ,  0.04385321,  0.02485174,  0.03006113,
        -0.01859785, -0.01245942,  0.01755248,  0.04559081, -0.03148939],
       [ 0.01791817, -0.01954323, -0.0439586 , -0.01066151, -0.00040602,
        -0.02125261, -0.02847081,  0.04438033,  0.02990146,  0.02927512],
       [ 0.02614791, -0.015311  , -0.02671999, -0.01079929,  0.01963147,
        -0.04251781,  0.01549606,  0.00074265, -0.01068414,  0.03010098],
       [ 0.00789253, -0.04971359, -0.00026793,  0.01440183, -0.02602975,
        -0.0243909 , -0.04849962, -0.01046251