In [57]:
from tensorflow.keras.preprocessing.text import one_hot

In [58]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [59]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [60]:
## Define the vocabulary size
voc_size=10000

In [61]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [62]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1399, 6827, 4312, 9988],
 [1399, 6827, 4312, 9002],
 [1399, 1892, 4312, 4179],
 [4010, 9700, 5938, 6576, 9751],
 [4010, 9700, 5938, 6576, 4275],
 [1492, 1399, 4325, 4312, 9195],
 [5854, 8512, 9297, 6576]]

In [63]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [64]:
import numpy as np

In [65]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1399 6827 4312 9988]
 [   0    0    0    0 1399 6827 4312 9002]
 [   0    0    0    0 1399 1892 4312 4179]
 [   0    0    0 4010 9700 5938 6576 9751]
 [   0    0    0 4010 9700 5938 6576 4275]
 [   0    0    0 1492 1399 4325 4312 9195]
 [   0    0    0    0 5854 8512 9297 6576]]


In [66]:
## feature representation
dim=10

In [67]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [68]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [69]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 83ms/step


array([[[-0.01303046, -0.03252061, -0.0450189 , -0.00014875,
         -0.01328477, -0.02455559,  0.03355867,  0.01944545,
         -0.04974813,  0.03702824],
        [-0.01303046, -0.03252061, -0.0450189 , -0.00014875,
         -0.01328477, -0.02455559,  0.03355867,  0.01944545,
         -0.04974813,  0.03702824],
        [-0.01303046, -0.03252061, -0.0450189 , -0.00014875,
         -0.01328477, -0.02455559,  0.03355867,  0.01944545,
         -0.04974813,  0.03702824],
        [-0.01303046, -0.03252061, -0.0450189 , -0.00014875,
         -0.01328477, -0.02455559,  0.03355867,  0.01944545,
         -0.04974813,  0.03702824],
        [ 0.01573328,  0.04317046,  0.04691159, -0.00965438,
          0.04999385, -0.00355879, -0.03928933, -0.00239159,
          0.00370061, -0.00019505],
        [-0.01830918, -0.04252887, -0.04056752,  0.0323399 ,
         -0.0488825 ,  0.03153117,  0.02332873, -0.04400947,
         -0.04550038, -0.03365701],
        [-0.02927039,  0.01873085,  0.02160707,  0.0

In [70]:
embedded_docs[0]

array([   0,    0,    0,    0, 1399, 6827, 4312, 9988], dtype=int32)

In [71]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 18ms/step


array([[-0.01303046, -0.03252061, -0.0450189 , -0.00014875, -0.01328477,
        -0.02455559,  0.03355867,  0.01944545, -0.04974813,  0.03702824],
       [-0.01303046, -0.03252061, -0.0450189 , -0.00014875, -0.01328477,
        -0.02455559,  0.03355867,  0.01944545, -0.04974813,  0.03702824],
       [-0.01303046, -0.03252061, -0.0450189 , -0.00014875, -0.01328477,
        -0.02455559,  0.03355867,  0.01944545, -0.04974813,  0.03702824],
       [-0.01303046, -0.03252061, -0.0450189 , -0.00014875, -0.01328477,
        -0.02455559,  0.03355867,  0.01944545, -0.04974813,  0.03702824],
       [ 0.01573328,  0.04317046,  0.04691159, -0.00965438,  0.04999385,
        -0.00355879, -0.03928933, -0.00239159,  0.00370061, -0.00019505],
       [-0.01830918, -0.04252887, -0.04056752,  0.0323399 , -0.0488825 ,
         0.03153117,  0.02332873, -0.04400947, -0.04550038, -0.03365701],
       [-0.02927039,  0.01873085,  0.02160707,  0.03353281, -0.04666343,
        -0.03497213, -0.04379931,  0.04575839